
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fabric
  name: cloud-fabric-ca
  annotations:
    k8s.eip.work/workload: cloud-fabric-ca
    k8s.eip.work/displayName: Fabric CA
    k8s.eip.work/service: ClusterIP
    k8s.eip.work/ingress: 'false'
  labels:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: cloud-fabric-ca
spec:
  selector:
    matchLabels:
      k8s.eip.work/layer: cloud
      k8s.eip.work/name: cloud-fabric-ca
  template:
    metadata:
      labels:
        k8s.eip.work/layer: cloud
        k8s.eip.work/name: cloud-fabric-ca
    spec:
      securityContext:
        seLinuxOptions: {}
      imagePullSecrets:
        - {}
      restartPolicy: Always
      initContainers: []
      containers:
        - image: 'hyperledger/fabric-ca:latest'
          imagePullPolicy: IfNotPresent
          name: fabric-ca
          volumeMounts:
            - name: ca
              mountPath: /etc/hyperledger/fabric-ca-server
              mountPropagation: None
            - name: crypto-config
              mountPath: /etc/hyperledger/fabric-tools/config
          command:
            - fabric-ca-server
            - start
            - '-b'
            - 'kexin228:kexin228'
          resources:
            limits:
            requests:
          env: []
      volumes:
        - name: ca
          hostPath:
            path: /root/containers_volume/fabric/ca
            type: Directory
        - name: crypto-config
          hostPath:
            path: /root/containers_volume/fabric/tools/crypto-config
            type: Directory
      terminationGracePeriodSeconds: 30
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  namespace: fabric
  name: cloud-fabric-ca
  annotations:
    k8s.eip.work/workload: cloud-fabric-ca
    k8s.eip.work/displayName: Fabric CA
  labels:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: cloud-fabric-ca
spec:
  selector:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: cloud-fabric-ca
  type: ClusterIP
  ports:
    - port: 7054
      targetPort: 7054
      protocol: TCP
      name: twgmbb
      nodePort: 0

