
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fabric
  name: orderer
  annotations:
    k8s.eip.work/workload: orderer
    k8s.eip.work/displayName: Orderer
    k8s.eip.work/service: NodePort
    k8s.eip.work/ingress: 'false'
  labels:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: orderer
spec:
  selector:
    matchLabels:
      k8s.eip.work/layer: cloud
      k8s.eip.work/name: orderer
  template:
    metadata:
      labels:
        k8s.eip.work/layer: cloud
        k8s.eip.work/name: orderer
    spec:
      securityContext:
        seLinuxOptions: {}
      imagePullSecrets:
        - {}
      restartPolicy: Always
      initContainers: []
      # hostAliases:
      #   - ip: "127.0.0.1"
      #     hostnames: 
      #       - orderer.example.com
      #       - peer0.org1.example.com
      containers:
        - image: 'hyperledger/fabric-orderer:latest'
          imagePullPolicy: IfNotPresent
          name: orderer
          volumeMounts:
            - name: channel-artifacts
              mountPath: /etc/hyperledger/configtx
            - name: orderer-org
              mountPath: /etc/hyperledger/msp
          resources:
            limits:
            requests:
          command: 
            - orderer
            - start
          env: 
            - name: ORDERER_GENERAL_LOGLEVEL
              value: "DEBUG"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "file"
            - name: ORDERER_GENERAL_GENESISFILE
              value: "/etc/hyperledger/configtx/fabricchannel.block"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "OrdererMSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/etc/hyperledger/msp/ordererOrganizations/example.com/orderers/orderer.example.com/msp"
            - name: ORDERER_GENERAL_LEDGERTYPE
              value: "file"
            - name: ORDERER_GENERAL_BATCHTIMEOUT
              value: "2s"
            - name: ORDERER_GENERAL_MAXMESSAGECOUNT
              value: "10"
            - name: ORDERER_GENERAL_MAXWINDOWSIZE
              value: "1000"
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "false"
            - name: ORDERER_RAMLEDGER_HISTORY_SIZE
              value: "100"
            - name: CONFIGTX_ORDERER_ORDERERTYPE
              value: "solo"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/etc/hyperledger/msp/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/etc/hyperledger/msp/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/etc/hyperledger/msp/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt]"
      volumes:
        - name: channel-artifacts
          hostPath:
            path: /root/fabric/tools/channel-artifacts
            type: Directory
        - name: orderer-org
          hostPath:
            path: /root/fabric/tools/crypto-config
            type: Directory
      terminationGracePeriodSeconds: 30
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  namespace: fabric
  name: orderer
  annotations:
    k8s.eip.work/workload: orderer
    k8s.eip.work/displayName: Orderer
  labels:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: orderer
spec:
  selector:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: orderer
  type: NodePort
  ports:
    - port: 7050
      targetPort: 7050
      protocol: TCP
      name: 8bdatz
      nodePort: 30705

