
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fabric
  name: peer0
  annotations:
    k8s.eip.work/workload: peer0
    k8s.eip.work/displayName: Peer0
    k8s.eip.work/service: NodePort
    k8s.eip.work/ingress: 'false'
  labels:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: peer0
spec:
  selector:
    matchLabels:
      k8s.eip.work/layer: cloud
      k8s.eip.work/name: peer0
  template:
    metadata:
      labels:
        k8s.eip.work/layer: cloud
        k8s.eip.work/name: peer0
    spec:
      securityContext:
        seLinuxOptions: {}
      imagePullSecrets:
        - {}
      restartPolicy: Always
      initContainers: []
      hostAliases:
        - ip: "127.0.0.1"
          hostnames: 
            - peer0.org1.example.com
        - ip: "192.168.50.251"
          hostnames: 
            - orderer.example.com
      containers:
        - image: 'hyperledger/fabric-peer:latest'
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          imagePullPolicy: IfNotPresent
          name: peer0
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run
            - name: peer-org
              mountPath: /etc/hyperledger/msp     
            - name: channel-artifacts
              mountPath: /etc/hyperledger/channel-artifacts
          command:
            - peer
            - node
            - start
            # - /bin/bash
            # - '-c'
            # - while true; do sleep 20191116; done
          resources:
            limits:
            requests:
          env: 
            - name: CORE_VM_ENDPOINT
              value: unix:///var/run/docker.sock
            - name: CORE_PEER_ID
              value: "peer0.org1.example.com"
            - name: CORE_PEER_ADDRESS
              value: "peer0.org1.example.com:7051"
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/msp/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer0.org1.example.com:7051"
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: "peer0.org1.example.com:7051"
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: "peer0.org1.example.com:8000"
            # - name: CORE_VM_HOSTCONFIG_DNS
            #   value: 139.59.77.160
            - name: CORE_PEER_LOCALMSPID
              value: "Org1MSP"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_LOGGING_LEVEL
              value: "DEBUG"
            # - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
            #   value: "bridge"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/etc/hyperledger/msp/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/etc/hyperledger/msp/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/etc/hyperledger/msp/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      volumes:
        - name: docker-sock
          hostPath:
            path: /root/fabric/peer/peer0/var/run
            type: Directory
        - name: peer-org
          hostPath:
            path: /root/fabric/tools/crypto-config
            type: Directory
        - name: channel-artifacts
          hostPath:
            path: /root/fabric/tools/channel-artifacts
            type: Directory    
      terminationGracePeriodSeconds: 30
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  namespace: fabric
  name: peer0
  annotations:
    k8s.eip.work/workload: peer0
    k8s.eip.work/displayName: Peer0
  labels:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: peer0
spec:
  selector:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: peer0
  type: NodePort
  ports:
    - port: 7051
      targetPort: 7051
      protocol: TCP
      name: djcn7b
      nodePort: 30751
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: djcn6b
      nodePort: 30800    

