
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fabric
  name: cli
  annotations:
    k8s.eip.work/workload: cli
    k8s.eip.work/displayName: Fabric Tools
    k8s.eip.work/service: none
    k8s.eip.work/ingress: 'false'
  labels:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: cli
spec:
  selector:
    matchLabels:
      k8s.eip.work/layer: cloud
      k8s.eip.work/name: cli
  template:
    metadata:
      labels:
        k8s.eip.work/layer: cloud
        k8s.eip.work/name: cli
    spec:
      securityContext:
        seLinuxOptions: {}
      imagePullSecrets: []
      restartPolicy: Always
      initContainers: []
      hostAliases:
        - ip: "10.96.0.10"
          hostnames:
            - peer0.org1.example.com
      containers:
        - image: 'hyperledger/fabric-tools:1.4'
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          imagePullPolicy: IfNotPresent
          name: fbc-tools
          volumeMounts:
            - name: chaincode
              mountPath: /opt/gopath/src/chaincode/go/
            - name: crypto
              mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - name: scripts
              mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - name: channel-artifacts
              mountPath: >-
                /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
            - name: configtx
              mountPath: /etc/hyperledger/fabric/configtx.yaml
            - name: crypto-config
              mountPath: /etc/hyperledger/fabric/crypto-config.yaml
            - name: docker-sock
              mountPath: /var/run
          command:
            - /bin/bash
            - '-c'
            - while true; do sleep 20191116; done
          resources:
            limits:
            requests:
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_VM_ENDPOINT
              value: unix:///var/run/docker.sock
            - name: CORE_PEER_ID
              value: cli
            - name: CORE_PEER_ADDRESS
              value: "peer0.org1.example.com:30751"
            - name: CORE_PEER_LOCALMSPID
              value: "Org1MSP"
            - name: CORE_PEER_TLS_ENABLED
              value: "false"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp"
          securityContext:
            seLinuxOptions: {}
      volumes:
        - name: chaincode
          hostPath:
            path: /Users/dujiao/Downloads/fabric/hyperledger/fabric/chaincode
        - name: crypto
          hostPath:
            path: /Users/dujiao/Downloads/fabric/hyperledger/fabric/crypto-config
            type: Directory
        - name: scripts
          hostPath:
            path: /Users/dujiao/Downloads/fabric/hyperledger/fabric/scripts
            type: Directory
        - name: channel-artifacts
          hostPath:
            path: /Users/dujiao/Downloads/fabric/hyperledger/fabric/channel-artifacts
            type: Directory
        - name: configtx
          hostPath:
            path: /Users/dujiao/Downloads/fabric/hyperledger/yaml/configtx.yaml
            type: File
        - name: crypto-config
          hostPath:
            path: /Users/dujiao/Downloads/fabric/hyperledger/yaml/crypto-config.yaml
            type: File
        - name: docker-sock
          hostPath:
            path: /Users/dujiao/Downloads/fabric/hyperledger/fabric/docker-sock
            type: Directory
      terminationGracePeriodSeconds: 30
  replicas: 1
